export type ContentField = {
  key: string;
  label: string;
  def: string;
  multiline?: boolean;
};

export type ContentGroup = {
  id: string;
  label: string;
  fields: ContentField[];
};

export const contentGroups: ContentGroup[] = [
  {
    id: "global",
    label: "Nagłówek i stopka",
    fields: [
      { key: "nav.home", label: "Menu — Home", def: "Home" },
      { key: "nav.about", label: "Menu — O mnie", def: "O mnie" },
      { key: "nav.offer", label: "Menu — Oferta", def: "Oferta" },
      { key: "nav.gallery", label: "Menu — Galeria", def: "Galeria" },
      { key: "nav.contact", label: "Menu — Kontakt", def: "Kontakt" },
      { key: "nav.cta", label: "Przycisk w menu", def: "Zarezerwuj termin" },
      {
        key: "footer.tagline",
        label: "Stopka — opis",
        def: "DJ • Wodzirej • Konferansjer. To nie tylko muzyka — to przeżycie.",
        multiline: true,
      },
      { key: "contact.phone", label: "Telefon", def: "515 646 970" },
      { key: "contact.facebook", label: "Facebook", def: "facebook.com/djinny.klimek" },
      { key: "contact.www", label: "Strona WWW", def: "www.djinny.pl" },
      { key: "contact.area", label: "Obszar działania", def: "Dolny Śląsk i cała Polska" },
      { key: "footer.realizations.title", label: "Stopka — nagłówek realizacji", def: "Realizacje" },
      {
        key: "footer.realizations.1",
        label: "Stopka — realizacje 1",
        def: "Wesela • Imprezy firmowe • Urodziny",
      },
      {
        key: "footer.realizations.2",
        label: "Stopka — realizacje 2",
        def: "Studniówki • Biesiady śpiewane przy stołach",
      },
      {
        key: "footer.realizations.3",
        label: "Stopka — realizacje 3",
        def: "Autorskie gry, konkursy i zabawy",
      },
      {
        key: "footer.copyright",
        label: "Stopka — prawa autorskie",
        def: "DJ INNY — Krzysztof Klimek. Wszelkie prawa zastrzeżone.",
      },
    ],
  },
  {
    id: "home-hero",
    label: "Strona główna — pierwszy widok",
    fields: [
      { key: "home.hero.kicker", label: "Nadtytuł", def: "DJ • WODZIREJ • KONFERANSJER" },
      { key: "home.hero.title1", label: "Nagłówek — część 1", def: "To nie tylko muzyka —" },
      { key: "home.hero.title2", label: "Nagłówek — część złota", def: "to przeżycie" },
      {
        key: "home.hero.lead",
        label: "Opis",
        def: "Tańczą nawet ci, którzy nigdy nie tańczą. Tworzę imprezy, o których mówi się jeszcze długo — z klasą, humorem i perfekcyjną organizacją.",
        multiline: true,
      },
      { key: "home.hero.cta1", label: "Przycisk 1", def: "Zarezerwuj termin" },
      { key: "home.hero.cta2", label: "Przycisk 2", def: "Zobacz ofertę" },
    ],
  },
  {
    id: "home-atuty",
    label: "Strona główna — atuty",
    fields: [
      { key: "home.atut.1.t", label: "Atut 1 — tytuł", def: "Prowadzenie z klasą" },
      { key: "home.atut.1.d", label: "Atut 1 — opis", def: "Elegancja, humor i wyczucie momentu." },
      { key: "home.atut.2.t", label: "Atut 2 — tytuł", def: "Głos i prezencja" },
      {
        key: "home.atut.2.d",
        label: "Atut 2 — opis",
        def: "Wyrazisty głos i świetna dykcja sceniczna.",
      },
      { key: "home.atut.3.t", label: "Atut 3 — tytuł", def: "Oprawa wizualna" },
      {
        key: "home.atut.3.d",
        label: "Atut 3 — opis",
        def: "Światło i efekty, które robią różnicę.",
      },
      { key: "home.atut.4.t", label: "Atut 4 — tytuł", def: "Pełen profesjonalizm" },
      {
        key: "home.atut.4.d",
        label: "Atut 4 — opis",
        def: "Doświadczenie, niezawodny sprzęt, energia.",
      },
      { key: "home.atut.5.t", label: "Atut 5 — tytuł", def: "Klimat i kontakt" },
      { key: "home.atut.5.d", label: "Atut 5 — opis", def: "Z gośćmi na najwyższym poziomie." },
      { key: "home.atut.6.t", label: "Atut 6 — tytuł", def: "Najlepsza muzyka" },
      {
        key: "home.atut.6.d",
        label: "Atut 6 — opis",
        def: "Dobór repertuaru dla każdego pokolenia.",
      },
    ],
  },
  {
    id: "home-oferta",
    label: "Strona główna — oferta",
    fields: [
      { key: "home.offer.kicker", label: "Nadtytuł", def: "Oferta" },
      { key: "home.offer.title", label: "Nagłówek", def: "Wybierz imprezę, o której marzysz" },
      { key: "home.offer.1.t", label: "Karta 1 — tytuł", def: "Wesela" },
      {
        key: "home.offer.1.d",
        label: "Karta 1 — opis",
        def: "Kompleksowa oprawa muzyczna i prowadzenie wesela z klasą, humorem i energią.",
        multiline: true,
      },
      { key: "home.offer.2.t", label: "Karta 2 — tytuł", def: "Imprezy firmowe" },
      {
        key: "home.offer.2.d",
        label: "Karta 2 — opis",
        def: "Jubileusze, bankiety i gale. Elegancka oprawa na najwyższym poziomie.",
        multiline: true,
      },
      { key: "home.offer.3.t", label: "Karta 3 — tytuł", def: "Studniówki i urodziny" },
      {
        key: "home.offer.3.d",
        label: "Karta 3 — opis",
        def: "Dynamiczna zabawa, najnowsze hity i sprawdzone klasyki.",
        multiline: true,
      },
      { key: "home.offer.more", label: "Link „więcej”", def: "Dowiedz się więcej →" },
    ],
  },
  {
    id: "home-historia",
    label: "Strona główna — moja historia",
    fields: [
      { key: "home.story.kicker", label: "Nadtytuł", def: "Moja historia" },
      { key: "home.story.title", label: "Nagłówek", def: "Krzysztof Klimek" },
      {
        key: "home.story.p1",
        label: "Akapit 1",
        def: "Moja przygoda z muzyką i sceną zaczęła się, gdy miałem zaledwie 13 lat. Pierwsze imprezy, pierwsze emocje i pierwszy kontakt z ludźmi utwierdziły mnie w przekonaniu, że to jest moja droga.",
        multiline: true,
      },
      {
        key: "home.story.p2",
        label: "Akapit 2",
        def: "Przez wiele lat śpiewałem i grałem na keyboardzie w zespole muzycznym. Z czasem odkryłem DJ-owanie — połączenie muzyki, techniki i prowadzenia imprezy, które pozwala mi w pełni realizować moją pasję.",
        multiline: true,
      },
      {
        key: "home.story.p3",
        label: "Akapit 3",
        def: "Uwielbiam ludzi i muzykę — to one napędzają mnie od ponad 31 lat. Największą satysfakcją jest dla mnie moment, gdy parkiet tętni życiem, a goście bawią się razem od pierwszego do ostatniego utworu.",
        multiline: true,
      },
      { key: "home.story.stat1.n", label: "Licznik 1 — liczba", def: "31" },
      { key: "home.story.stat1.l", label: "Licznik 1 — opis", def: "lat doświadczenia" },
      { key: "home.story.stat2.n", label: "Licznik 2 — liczba", def: "500+" },
      { key: "home.story.stat2.l", label: "Licznik 2 — opis", def: "imprez" },
      { key: "home.story.stat3.n", label: "Licznik 3 — liczba", def: "100%" },
      { key: "home.story.stat3.l", label: "Licznik 3 — opis", def: "zaangażowania" },
      { key: "home.story.cta", label: "Przycisk", def: "Poznaj mnie lepiej" },
    ],
  },
  {
    id: "home-faq",
    label: "Strona główna — FAQ",
    fields: [
      { key: "home.faq.kicker", label: "Nadtytuł", def: "FAQ" },
      { key: "home.faq.title", label: "Nagłówek", def: "Najczęstsze pytania" },
      { key: "home.faq.1.q", label: "Pytanie 1", def: "Jaki rodzaj muzyki gracie?" },
      {
        key: "home.faq.1.a",
        label: "Odpowiedź 1",
        def: "Repertuar dobieram do gości i charakteru imprezy — od ponadczasowych klasyków, przez disco polo, po najnowsze światowe hity.",
        multiline: true,
      },
      { key: "home.faq.2.q", label: "Pytanie 2", def: "Czy dojeżdżasz do innych miast?" },
      {
        key: "home.faq.2.a",
        label: "Odpowiedź 2",
        def: "Tak — obsługuję cały Dolny Śląsk, a na życzenie dojeżdżam w dowolne miejsce w Polsce.",
        multiline: true,
      },
      { key: "home.faq.3.q", label: "Pytanie 3", def: "Czy prowadzisz zabawy podczas imprezy?" },
      {
        key: "home.faq.3.a",
        label: "Odpowiedź 3",
        def: "Oczywiście. Zabawy dobieram z wyczuciem — nigdy nachalnie, zawsze tak, by goście świetnie się bawili.",
        multiline: true,
      },
      {
        key: "home.faq.4.q",
        label: "Pytanie 4",
        def: "Czy możemy omówić szczegóły i plan imprezy przed wydarzeniem?",
      },
      {
        key: "home.faq.4.a",
        label: "Odpowiedź 4",
        def: "Zawsze spotykamy się (osobiście lub online), by dopiąć harmonogram, listę utworów i wszystkie życzenia.",
        multiline: true,
      },
    ],
  },
  {
    id: "home-opinie",
    label: "Strona główna — opinie i CTA",
    fields: [
      { key: "home.reviews.kicker", label: "Nadtytuł", def: "Opinie" },
      { key: "home.reviews.title", label: "Nagłówek", def: "Co mówią klienci" },
      { key: "home.review.1.n", label: "Opinia 1 — autor", def: "Anna" },
      {
        key: "home.review.1.t",
        label: "Opinia 1 — treść",
        def: "Najlepszy wybór na nasze wesele! Goście bawili się do białego rana. Polecamy z całego serca!",
        multiline: true,
      },
      { key: "home.review.2.n", label: "Opinia 2 — autor", def: "Sławek" },
      {
        key: "home.review.2.t",
        label: "Opinia 2 — treść",
        def: "Pełen profesjonalizm. Wszyscy goście chwalili muzykę i prowadzenie.",
        multiline: true,
      },
      { key: "home.review.3.n", label: "Opinia 3 — autor", def: "Magda i Paweł" },
      {
        key: "home.review.3.t",
        label: "Opinia 3 — treść",
        def: "Zabawy nie były nachalne, a parkiet cały czas pełny. Dziękujemy!",
        multiline: true,
      },
      { key: "home.cta.title1", label: "CTA — nagłówek 1", def: "Zadbajmy razem" },
      { key: "home.cta.title2", label: "CTA — nagłówek 2", def: "o niezapomnianą imprezę" },
      {
        key: "home.cta.lead",
        label: "CTA — opis",
        def: "Twój wyjątkowy dzień zasługuje na oprawę, która przerośnie oczekiwania.",
        multiline: true,
      },
      { key: "home.cta.button", label: "CTA — przycisk", def: "Sprawdź dostępny termin" },
    ],
  },
  {
    id: "about",
    label: "Podstrona — O mnie",
    fields: [
      { key: "about.kicker", label: "Nadtytuł", def: "Moja historia" },
      { key: "about.title", label: "Nagłówek", def: "Krzysztof Klimek" },
      {
        key: "about.lead",
        label: "Wstęp",
        def: "DJ, wodzirej i konferansjer. Prowadzę imprezy, na których tańczą nawet ci, którzy nigdy nie tańczą.",
        multiline: true,
      },
      {
        key: "about.p1",
        label: "Akapit 1",
        def: "Moja przygoda z muzyką i sceną zaczęła się bardzo wcześnie. Pierwsze imprezy, pierwsze emocje i pierwszy kontakt z ludźmi utwierdziły mnie w przekonaniu, że to jest moja droga.",
        multiline: true,
      },
      {
        key: "about.p2",
        label: "Akapit 2",
        def: "Przez wiele lat śpiewałem i grałem na keyboardzie w zespole muzycznym. Z czasem odkryłem DJ-owanie — połączenie muzyki, techniki i prowadzenia imprezy, które pozwala mi w pełni realizować moją pasję.",
        multiline: true,
      },
      {
        key: "about.p3",
        label: "Akapit 3",
        def: "Uwielbiam ludzi i muzykę. Największą satysfakcją jest dla mnie moment, gdy parkiet tętni życiem, a goście bawią się razem od pierwszego do ostatniego utworu.",
        multiline: true,
      },
      {
        key: "about.p4",
        label: "Akapit wyróżniony",
        def: "Zaufanie, które otrzymuję, jest dla mnie największym wyróżnieniem.",
        multiline: true,
      },
      { key: "about.stat1.n", label: "Licznik 1 — liczba", def: "30+" },
      { key: "about.stat1.l", label: "Licznik 1 — opis", def: "lat na scenie" },
      { key: "about.stat2.n", label: "Licznik 2 — liczba", def: "500+" },
      { key: "about.stat2.l", label: "Licznik 2 — opis", def: "poprowadzonych imprez" },
      { key: "about.stat3.n", label: "Licznik 3 — liczba", def: "100%" },
      { key: "about.stat3.l", label: "Licznik 3 — opis", def: "zaangażowania" },
      { key: "about.cta", label: "Przycisk", def: "Porozmawiajmy o Twojej imprezie" },
    ],
  },
  {
    id: "offer",
    label: "Podstrona — Oferta",
    fields: [
      { key: "offer.kicker", label: "Nadtytuł", def: "Oferta" },
      { key: "offer.title", label: "Nagłówek", def: "Wybierz imprezę, o której marzysz" },
      {
        key: "offer.lead",
        label: "Wstęp",
        def: "Każde wydarzenie przygotowuję indywidualnie — od repertuaru po scenariusz i oprawę wizualną.",
        multiline: true,
      },
      { key: "offer.1.t", label: "Pakiet 1 — tytuł", def: "Oferta weselna" },
      {
        key: "offer.1.d",
        label: "Pakiet 1 — opis",
        def: "Kompleksowa oprawa muzyczna i prowadzenie wesela.",
        multiline: true,
      },
      { key: "offer.1.p1", label: "Pakiet 1 — punkt 1", def: "Prowadzenie z klasą i humorem" },
      { key: "offer.1.p2", label: "Pakiet 1 — punkt 2", def: "Muzyka dla każdego pokolenia" },
      { key: "offer.1.p3", label: "Pakiet 1 — punkt 3", def: "Autorskie gry i konkursy" },
      { key: "offer.1.p4", label: "Pakiet 1 — punkt 4", def: "Oprawa świetlna i ciężki dym" },
      { key: "offer.2.t", label: "Pakiet 2 — tytuł", def: "Imprezy firmowe" },
      {
        key: "offer.2.d",
        label: "Pakiet 2 — opis",
        def: "Jubileusze, bankiety, gale i eventy okolicznościowe.",
        multiline: true,
      },
      { key: "offer.2.p1", label: "Pakiet 2 — punkt 1", def: "Elegancka konferansjerka" },
      { key: "offer.2.p2", label: "Pakiet 2 — punkt 2", def: "Dopasowany repertuar" },
      { key: "offer.2.p3", label: "Pakiet 2 — punkt 3", def: "Nagłośnienie sal do 300 osób" },
      { key: "offer.2.p4", label: "Pakiet 2 — punkt 4", def: "Współpraca z organizatorem" },
      { key: "offer.3.t", label: "Pakiet 3 — tytuł", def: "Studniówki i urodziny" },
      {
        key: "offer.3.d",
        label: "Pakiet 3 — opis",
        def: "Dynamiczna zabawa i najnowsze hity.",
        multiline: true,
      },
      { key: "offer.3.p1", label: "Pakiet 3 — punkt 1", def: "Polonez i oficjalna część" },
      { key: "offer.3.p2", label: "Pakiet 3 — punkt 2", def: "Najnowsze hity i klasyki" },
      { key: "offer.3.p3", label: "Pakiet 3 — punkt 3", def: "Efekty specjalne" },
      { key: "offer.3.p4", label: "Pakiet 3 — punkt 4", def: "Energia od pierwszej minuty" },
      { key: "offer.cta", label: "Przycisk pakietu", def: "Zapytaj o termin" },
      { key: "offer.extras.kicker", label: "Dodatki — nadtytuł", def: "Dodatki" },
      { key: "offer.extras.title", label: "Dodatki — nagłówek", def: "Oprawa, która robi różnicę" },
      { key: "offer.extra.1", label: "Dodatek 1", def: "Biesiady śpiewane przy stołach" },
      { key: "offer.extra.2", label: "Dodatek 2", def: "Ciężki dym do pierwszego tańca" },
      { key: "offer.extra.3", label: "Dodatek 3", def: "Fontanny iskier" },
      { key: "offer.extra.4", label: "Dodatek 4", def: "Miny dymne i konfetti" },
      { key: "offer.extra.5", label: "Dodatek 5", def: "Oświetlenie dekoracyjne sali" },
      { key: "offer.extra.6", label: "Dodatek 6", def: "Nagłośnienie ceremonii plenerowej" },
    ],
  },
  {
    id: "gallery",
    label: "Podstrona — Galeria",
    fields: [
      { key: "gallery.kicker", label: "Nadtytuł", def: "Galeria" },
      { key: "gallery.title", label: "Nagłówek", def: "Momenty, które zostają" },
      {
        key: "gallery.lead",
        label: "Wstęp",
        def: "Kilka kadrów z imprez, które miałem przyjemność poprowadzić.",
        multiline: true,
      },
      {
        key: "gallery.note",
        label: "Notka pod zdjęciami",
        def: "Więcej zdjęć i relacji znajdziesz na moim profilu na Facebooku.",
        multiline: true,
      },
    ],
  },
  {
    id: "contact",
    label: "Podstrona — Kontakt",
    fields: [
      { key: "contact.kicker", label: "Nadtytuł", def: "Skontaktuj się" },
      { key: "contact.title", label: "Nagłówek", def: "Sprawdź dostępny termin" },
      {
        key: "contact.lead",
        label: "Wstęp",
        def: "Napisz lub zadzwoń — chętnie opowiem, jak może wyglądać Twoja impreza.",
        multiline: true,
      },
      { key: "contact.box.title", label: "Nagłówek karty", def: "Dane kontaktowe" },
      { key: "contact.cta", label: "Przycisk", def: "Zadzwoń teraz" },
      { key: "contact.faq.kicker", label: "FAQ — nadtytuł", def: "FAQ" },
      { key: "contact.faq.1.q", label: "Pytanie 1", def: "Jaki rodzaj muzyki gracie?" },
      {
        key: "contact.faq.1.a",
        label: "Odpowiedź 1",
        def: "Repertuar dobieram do gości — od klasyki po najnowsze hity.",
        multiline: true,
      },
      { key: "contact.faq.2.q", label: "Pytanie 2", def: "Czy dojeżdżasz do innych miast?" },
      {
        key: "contact.faq.2.a",
        label: "Odpowiedź 2",
        def: "Tak, działam na Dolnym Śląsku i w całej Polsce.",
        multiline: true,
      },
      { key: "contact.faq.3.q", label: "Pytanie 3", def: "Czy prowadzisz zabawy podczas imprezy?" },
      {
        key: "contact.faq.3.a",
        label: "Odpowiedź 3",
        def: "Tak — autorskie gry, konkursy i zabawy z klasą.",
        multiline: true,
      },
      { key: "contact.faq.4.q", label: "Pytanie 4", def: "Czy omawiamy plan imprezy wcześniej?" },
      {
        key: "contact.faq.4.a",
        label: "Odpowiedź 4",
        def: "Zawsze. Scenariusz ustalamy wspólnie przed terminem.",
        multiline: true,
      },
    ],
  },
];

export const contentDefaults: Record<string, string> = Object.fromEntries(
  contentGroups.flatMap((g) => g.fields.map((f) => [f.key, f.def])),
);
